import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "@/styles/globals.css";
import Providers from "./providers";
import Header from "@/app/components/header";
import Footer from "./components/footer";
import { AuthProvider } from "./contexts/auth.context";
import { JobsProvider } from "./contexts/jobs.context";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "AlbirJobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${plusJakarta.variable} ${inter.variable}`}>
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className} bg-gray-100 text-gray-900 flex flex-col min-h-screen`}>
        <Providers>
          <AuthProvider>
            <JobsProvider>
              <Header />
              <main className="flex-grow">
                {children}
              </main>
              <Footer />
            </JobsProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
